const PROFILE_TAB = 'PROFILE';
const ACTIVATION_TABLE = 'ACT_TABLE';
const NEW_USER = 'NEW_USER';
const USER_TABLE = 'USER_TABLE';
const SELLER_STAT = 'SELLER_STAT';
const ADD_SVG = 'ADD_SVG';
const SERVICES = 'SERVICES';

export { PROFILE_TAB, ACTIVATION_TABLE, NEW_USER, USER_TABLE, ADD_SVG, SERVICES, SELLER_STAT }